[package]
name = "usuarios-application"
version = "0.1.0"
edition = "2021"

[dependencies]
usuarios-domain = { path = "../domain" }
usuarios-auth = { path = "../auth" }

async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true}
