[package]
name = "usuarios-application"
version = "0.1.0"
edition = "2021"

[dependencies]
usuarios-domain = { path = "../domain" }
usuarios-auth = { path = "../auth" }

async-trait = "0.1"

[dev-dependencies]
tokio = { version = "1.41", features = ["full"] }
