[workspace]
members = [
    "crates/features/salas/domain",
    "crates/features/salas/application",
    "crates/features/salas/infrastructure",
    "crates/features/salas/api",
    "crates/app",
    "crates/app-cli",
    "crates/app-tui",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
axum = "0.8.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
