[package]
name = "salas-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# Capas de tu feature
salas-domain = { path = "../domain" }
salas-application = { path = "../application" }
salas-infrastructure = { path = "../infrastructure" }

# Serializaci√≥n (DTOs)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Framework web
axum = { workspace = true , features = ["macros"] }
tokio = { version = "1", features = ["full"] }

# UUID para IDs
uuid = { version = "1.0", features = ["v4", "serde"] }

# Manejo de errores HTTP
http = "1.0"
thiserror = "2.0"

# Logging (opcional pero recomendado)
tracing = "0.1"