[package]
name = "salas-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# Capas de tu feature
salas-domain = { path = "../domain" }
salas-application = { path = "../application" }
salas-infrastructure = { path = "../infrastructure" }

# Serialización (DTOs)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Framework web
axum = { workspace = true , features = ["macros"] }
tokio = { version = "1", features = ["full"] }
async-trait = { workspace = true }

# UUID para IDs
uuid = { version = "1.0", features = ["v4", "serde"] }

# Manejo de errores HTTP
http = "1.0"
thiserror = "2.0"

# Logging (opcional pero recomendado)
tracing = { workspace = true }

# OpenAPI / Swagger
utoipa = { version = "5.3", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "9.0", features = ["axum"] }

# Autenticación
usuarios-auth = { path = "../../usuarios/auth" }
usuarios-domain = { path = "../../usuarios/domain" }
