[package]
name = "app-tui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "reservas-tui"
path = "src/main.rs"

[dependencies]
ratatui = "0.25"
crossterm = "0.27"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tonic = "0.12"
usuarios-grpc = { path = "../features/usuarios/grpc" }
