[package]
name = "salas-domain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
validator = { workspace = true, features = ["derive"] }
utoipa = { workspace = true, features = ["uuid"] }
