[package]
name = "salas-domain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
validator = { version = "0.16", features = ["derive"] }
utoipa = { version = "5", features = ["uuid"] }
