[package]
name = "reservas-application"
version = "0.1.0"
edition = "2021"

[dependencies]
reservas-domain = { path = "../domain" }
async-trait = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tokio = { workspace = true}
